### ISSUE TITLE
commit id How to assign it

### ISSUE THREAD

**Issue by yunshuo** [FudanSELab/CLDIFF#7]
How do you give an initial value to commitId?
IDEA  Keep reporting errors

at org.eclipse.jgit.lib.ObjectId.fromString(ObjectId.java:232)
at edu.fdu.se.git.JGitHelper.analyzeOneCommit(JGitHelper.java:84)

**Comment by Symbolk** [comment]
Similar error here:
```
org.eclipse.jgit.errors.MissingObjectException: Missing unknown e5d923aa8a90edcf431929610f40dfff44a4be14
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:160)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
org.eclipse.jgit.errors.MissingObjectException: Missing unknown e5d923aa8a90edcf431929610f40dfff44a4be14
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:160)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at edu.fdu.se.git.JGitHelper.analyzeOneCommit(JGitHelper.java:85)
	at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:32)
	at main.CLDIFFServerOffline.generateCLDIFFResult(CLDIFFServerOffline.java:82)
	at main.CLDIFFServerOffline$FetchMetaCacheHandler.handle(CLDIFFServerOffline.java:66)
```

**Comment by kaifeng-h** [comment]
MissingObjectException occurs when the commit id is not a valid commit id or your git repository is not valid. Check your commit id and ensure that the git repository path endswith _"/.git"_ suffix

**Comment by Symbolk** [comment]
@calvinhkf I am running the `CLDIFFServerOffline` on Windows with the following args:
```
D:\coding\gumtree\.git D:\temp\CLDiff
```
And then I start the tomcat app, visit `http://localhost:8080/CLDIFF-WEB/indexoffline.html`, the webpage show itself. However, whatever commit id I input (say, `8ba45cd6f1186b0caef72b07730dc65facf9820c`, which is valid for sure as well as the repo path), it always leads to this error.

**Comment by kaifeng-h** [comment]
Arguments order should be reversed.1st argument is the output dir and the 2nd argument is a valid git repo path.  (Mistake in readme.  Will update soon)

**Comment by ZzillLongLee** [comment]
I also have a similar issue. 
I put 3 arguments into the run method as following these code lines:
        String repo = "D:/git/kr.ac.jbnu.ssel.misrac.git";
        String commitId = "e5a962f3c2b67b1d26b0237c0ee6352e16888b57";
        String outputDir = "D:/test/output";

Error:
org.eclipse.jgit.errors.MissingObjectException: Missing unknown e5a962f3c2b67b1d26b0237c0ee6352e16888b57
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:160)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at edu.fdu.se.git.JGitHelper.analyzeOneCommit(JGitHelper.java:85)
	at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:40)
	at main.CLDIFFCmd.main(CLDIFFCmd.java:17)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "parentCommits" is null
	at edu.fdu.se.base.preprocessingfile.data.FileOutputLog.setCommitId(FileOutputLog.java:38)
	at edu.fdu.se.cldiff.CLDiffAPI.<init>(CLDiffAPI.java:42)
	at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:41)
	at main.CLDIFFCmd.main(CLDIFFCmd.java:17)

**Comment by kaifeng-h** [comment]
Hi, @ZzillLongLee  Normally, the MissingObjectException is related to an invalid git repo or invalid commit id. So please check the existence of repo _D:/git/kr.ac.jbnu.ssel.misrac.git_. and commit _e5a962f3c2b67b1d26b0237c0ee6352e16888b57_ . The git repo usually ends with "/.git".

**Comment by ZzillLongLee** [comment]
Hello, calvinhkf.
Thank you for replying to my question.
However, I still stuck in this issue...
So, I'd like to know what is the invalid git repo and commit?
It's because, I've tried high ranked repository and its commit(e.g., apache
tomcat, google guava, ..etc.).
So, I leave my questions here:
1. What is invalid git and commit (*git*: is that URL or local git repo
*commit*: is that a commit uploaded in the master branch)
2. how do you put the parameter to run the "run" method?

**Comment by kaifeng-h** [comment]
Hi, @ZzillLongLee. Could you give an example of the MissingObjectException exception?  (Your tested repo path and commit id, the repo is a local dir path)

**Comment by ZzillLongLee** [comment]
Hello, calvinhkf.
Here is the example that I've faced exception.
repo path: D:\\git\\camel.git ( In order to get the local repo, I cloned
project from jgit)
commit ID: 67698db92c0865362b0db8773aee3d3811059cae (URL:
https://github.com/apache/camel/commit/67698db92c0865362b0db8773aee3d3811059cae
)
outputDir: D:\\test\\output

**Comment by ZzillLongLee** [comment]
Hello, calvinhkf.
I gotta say sorry first.
As you mentioned before, I put the wrong local repo dir.
I used to put ("D:\\git\\camel.git ") but the right input was
D:\\git\\camel\.git
So, it finally worked as I put the right input.

**Comment by kaifeng-h** [comment]
You’re welcome. :-)
