### ISSUE TITLE
Sometings wrong when i try to used CLDiff

### ISSUE THREAD

**Issue by gaolannning** [FudanSELab/CLDIFF#8]
I have tried to used it,but got this error?

java -cp CLDiffServerOnline.jar main.CLDIFFServerOffline   https://github.com/spring-projects/spring-framework.git  /home/test                                        FetchMetaCacheHandler
PostContent: url=3c1adf7f6af0dff9bda74f40dabe8cf428a62003
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
commitid3c1adf7f6af0dff9bda74f40dabe8cf428a62003
commitString3c1adf7f6af0dff9bda74f40dabe8cf428a62003
org.eclipse.jgit.errors.MissingObjectException: Missing unknown 3c1adf7f6af0dff9bda74f40dabe8cf428a62003
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:160)
        at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
        at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
        at edu.fdu.se.git.JGitHelper.analyzeOneCommit(JGitHelper.java:85)
        at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:40)
        at main.CLDIFFServerOffline.generateCLDIFFResult(CLDIFFServerOffline.java:89)
        at main.CLDIFFServerOffline$FetchMetaCacheHandler.handle(CLDIFFServerOffline.java:66)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:685)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:657)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:440)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:405)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at edu.fdu.se.base.preprocessingfile.data.FileOutputLog.setCommitId(FileOutputLog.java:38)
        at edu.fdu.se.cldiff.CLDiffAPI.<init>(CLDiffAPI.java:42)
        at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:41)
        at main.CLDIFFServerOffline.generateCLDIFFResult(CLDIFFServerOffline.java:89)
        at main.CLDIFFServerOffline$FetchMetaCacheHandler.handle(CLDIFFServerOffline.java:66)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:685)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:657)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:440)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:405)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by 3rdPartyLibs** [comment]
when you run CLDIFFServerOffline, the input argument corresponds to the local address of a git repository instead of an online url.

**Comment by kaifeng-h** [comment]
When you run CLDIFFServerOffline , the input parameter should be a **local**  git repo address instead of an online url.

**Comment by gaolannning** [comment]
can u give me a example ?

**Comment by gaolannning** [comment]
root@kali:~/CLDIFF-master/target# java -cp CLDiffServerOnline.jar main.CLDIFFServerOffline  /root/CLDIFF-master/.git  /home
FetchMetaCacheHandler
PostContent: url=ba45fefe5c5370af587b63c232be0081a8193a4c
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
commitidba45fefe5c5370af587b63c232be0081a8193a4c
commitStringba45fefe5c5370af587b63c232be0081a8193a4c
org.eclipse.jgit.errors.MissingObjectException: Missing unknown ba45fefe5c5370af587b63c232be0081a8193a4c
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:160)
        at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
        at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
        at edu.fdu.se.git.JGitHelper.analyzeOneCommit(JGitHelper.java:85)
        at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:40)
        at main.CLDIFFServerOffline.generateCLDIFFResult(CLDIFFServerOffline.java:89)
        at main.CLDIFFServerOffline$FetchMetaCacheHandler.handle(CLDIFFServerOffline.java:66)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:685)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:657)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:440)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:405)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at edu.fdu.se.base.preprocessingfile.data.FileOutputLog.setCommitId(FileOutputLog.java:38)
        at edu.fdu.se.cldiff.CLDiffAPI.<init>(CLDiffAPI.java:42)
        at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:41)
        at main.CLDIFFServerOffline.generateCLDIFFResult(CLDIFFServerOffline.java:89)
        at main.CLDIFFServerOffline$FetchMetaCacheHandler.handle(CLDIFFServerOffline.java:66)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:685)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:657)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:440)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:405)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by gaolannning** [comment]
> When you run CLDIFFServerOffline , the input parameter should be a **local** git repo address instead of an online url.

I  have tried but same error

**Comment by gaolannning** [comment]
root@kali:~/CLDIFF-master/src/main# cat CLDIFFCmd.java
package main;

import edu.fdu.se.base.common.Global;
import edu.fdu.se.cldiff.CLDiffLocal;

/**
 * Created by huangkaifeng on 2018/10/11.
 */
public class CLDIFFCmd {

    public static void main(String args[]){
        Global.runningMode = 0;
        String repo = "/root/CLDIFF-master/.git";
        String commitId = "ba45fefe5c5370af587b63c232be0081a8193a4c";
        String outputDir = "/home";
        CLDiffLocal CLDiffLocal = new CLDiffLocal();
        CLDiffLocal.run(commitId,repo,outputDir);
    }
}

root@kali:~/CLDIFF-master/target# java -cp CLDiffServerOnline.jar  main.CLDIFFCmd
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
commitidba45fefe5c5370af587b63c232be0081a8193a4c
commitStringba45fefe5c5370af587b63c232be0081a8193a4c
org.eclipse.jgit.errors.MissingObjectException: Missing unknown ba45fefe5c5370af587b63c232be0081a8193a4c
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:160)
        at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
        at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
        at edu.fdu.se.git.JGitHelper.analyzeOneCommit(JGitHelper.java:85)
        at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:40)
        at main.CLDIFFCmd.main(CLDIFFCmd.java:17)
Exception in thread "main" java.lang.NullPointerException
        at edu.fdu.se.base.preprocessingfile.data.FileOutputLog.setCommitId(FileOutputLog.java:38)
        at edu.fdu.se.cldiff.CLDiffAPI.<init>(CLDiffAPI.java:42)
        at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:41)
        at main.CLDIFFCmd.main(CLDIFFCmd.java:17)

**Comment by gaolannning** [comment]
I have test this ,it is ok
root@kali:~/CLDIFF-master/target# java -cp CLDiffServerOnline.jar  main.CLDIFFCmd
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
commitidba45fefe5c5370af587b63c232be0081a8193a4c
commitStringba45fefe5c5370af587b63c232be0081a8193a4c
ClusterUpDown.java
----pre-processing 299350457
----mapping 128082716
ActionSize:18
Delete> IfStatement: [D] from Block: (85,88)
Delete> MethodInvocation: [D] from IfStatement: [D] (85,85)
Delete> Block: [D] from IfStatement: [D] (85,88)
Delete> QualifiedName:Global.fileName [D] from MethodInvocation: [D] (85,85)
Delete> SimpleName:endsWith [D] from MethodInvocation: [D] (85,85)
Delete> StringLiteral:"XStreamMarshaller.java" [D] from MethodInvocation: [D] (85,85)
Delete> ExpressionStatement: [D] from Block: [D] (86,86)
Delete> ExpressionStatement: [D] from Block: [D] (87,87)
Delete> MethodInvocation: [D] from ExpressionStatement: [D] (86,86)
Delete> MethodInvocation: [D] from ExpressionStatement: [D] (87,87)
Delete> QualifiedName:System.out [D] from MethodInvocation: [D] (86,86)
Delete> SimpleName:println [D] from MethodInvocation: [D] (86,86)
Delete> InfixExpression:+ [D] from MethodInvocation: [D] (86,86)
Delete> SimpleName:fp [D] from MethodInvocation: [D] (87,87)
Delete> SimpleName:setActionTraversedMap [D] from MethodInvocation: [D] (87,87)
Delete> SimpleName:a [D] from MethodInvocation: [D] (87,87)
Delete> StringLiteral:"pass move " [D] from InfixExpression:+ [D] (86,86)
Delete> QualifiedName:Global.fileName [D] from InfixExpression:+ [D] (86,86)

Member key size:2
Change entity size:1
ClusterUpDown. MethodDeclaration: passGumtreePalsePositiveMoves (41,93) listSize:1
0. Delete If condition and body (85,88)

----grouping 10089540
Concise Code Differences:
0. deleteIf
        (85,88)


Links:



but still got error  in WEBGUI
root@kali:~/CLDIFF-master/target# java -cp CLDiffServerOnline.jar main.CLDIFFServerOffline  /home/CLDIFF/.git  /home/test
FetchMetaCacheHandler
PostContent: url=ba45fefe5c5370af587b63c232be0081a8193a4c
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
commitidba45fefe5c5370af587b63c232be0081a8193a4c
commitStringba45fefe5c5370af587b63c232be0081a8193a4c
org.eclipse.jgit.errors.MissingObjectException: Missing unknown ba45fefe5c5370af587b63c232be0081a8193a4c
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:160)
        at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
        at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
        at edu.fdu.se.git.JGitHelper.analyzeOneCommit(JGitHelper.java:85)
        at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:40)
        at main.CLDIFFServerOffline.generateCLDIFFResult(CLDIFFServerOffline.java:89)
        at main.CLDIFFServerOffline$FetchMetaCacheHandler.handle(CLDIFFServerOffline.java:66)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:685)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:657)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:440)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:405)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
        at edu.fdu.se.base.preprocessingfile.data.FileOutputLog.setCommitId(FileOutputLog.java:38)
        at edu.fdu.se.cldiff.CLDiffAPI.<init>(CLDiffAPI.java:42)
        at edu.fdu.se.cldiff.CLDiffLocal.run(CLDiffLocal.java:41)
        at main.CLDIFFServerOffline.generateCLDIFFResult(CLDIFFServerOffline.java:89)
        at main.CLDIFFServerOffline$FetchMetaCacheHandler.handle(CLDIFFServerOffline.java:66)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:685)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:657)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:440)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:405)
        at java.base/java.lang.Thread.run(Thread.java:844)

It is using same parameter,but still not same result

**Comment by kaifeng-h** [comment]
"/home/CLDIFF/.git" should be your input git repository where the commit id is from

**Comment by gaolannning** [comment]
> "/home/CLDIFF/.git" should be your input git repository where the commit id is from

Sure.
root@kali:~/CLDIFF-master/src/main# cat CLDIFFCmd.java 
package main;

import edu.fdu.se.base.common.Global;
import edu.fdu.se.cldiff.CLDiffLocal;

/**
 * Created by huangkaifeng on 2018/10/11.
 */
public class CLDIFFCmd {

    public static void main(String args[]){
        Global.runningMode = 0;
        String repo = "/home/CLDIFF/.git";
        String commitId = "ba45fefe5c5370af587b63c232be0081a8193a4c";
        String outputDir = "/home/test";
        CLDiffLocal CLDiffLocal = new CLDiffLocal();
        CLDiffLocal.run(commitId,repo,outputDir);
    }
}

I have tested in this file .

**Comment by gaolannning** [comment]
java -cp CLDiffServerOnline.jar main.CLDIFFServerOffline  /home/test  /home/CLDIFF/.git
This works,i got it wrong
